{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-guru-prometheus
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "traffic-guru.prometheus.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "traffic-guru.prometheus.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "traffic-guru.prometheus.labels" . | nindent 8 }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      containers:
      - name: prometheus
        ports:
        - containerPort: {{.Values.prometheus.port}}
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --storage.tsdb.retention.time={{.Values.prometheus.retention.time}}
        - --web.listen-address=:{{.Values.prometheus.port}}
        image: {{.Values.prometheus.image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "{{.Values.prometheus.resources.limits.cpu}}"
            memory: "{{.Values.prometheus.resources.limits.memory}}"
          requests:
            cpu: "{{.Values.prometheus.resources.requests.cpu}}"
            memory: "{{.Values.prometheus.resources.requests.memory}}"
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      serviceAccountName: traffic-guru-prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: traffic-guru-prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
      {{- if .Values.prometheus.affinity }}
      affinity:
      {{- toYaml .Values.prometheus.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.prometheus.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.prometheus.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.prometheus.tolerations }}
      tolerations:
      {{- toYaml .Values.prometheus.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
