apiVersion: v1
kind: Secret
metadata:
  name: traffic-guru-db-cred
type: Opaque
stringData:
  DATABASE_HOST: {{ include "traffic-guru.databaseHost" . | quote }}
  DATABASE_PORT: {{ include "traffic-guru.databasePort" . | quote }}
  DATABASE_USERNAME: {{ include "traffic-guru.databaseUser" . | quote }}
  DATABASE_PASSWORD: {{ include "traffic-guru.databasePassword" . | quote }}
  DATABASE_NAME: {{ include "traffic-guru.databaseName" . | quote }}
  DATABASE_TYPE: {{.Values.database.type}}  

