apiVersion: v1
kind: Secret
metadata:
  name: traffic-guru-ch-cred
type: Opaque
stringData:
  COMPONENT_CLICKHOUSE_HOST: "{{ .Release.Name}}-clickhouse"
  COMPONENT_CLICKHOUSE_PORT: "8123"
  COMPONENT_CLICKHOUSE_DATABASE: "default"
  COMPONENT_CLICKHOUSE_USER: {{ .Values.clickhouse.auth.username | quote }}
  COMPONENT_CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.auth.password | quote }}

