{
 "title": "OSM Service to Service Metrics",
 "description": "Compatible with OSM v1.0.0. This dashboard lets you view the traffic metrics from a given source service to a given destination service.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_namespace",
    "label": "Source Namespace",
    "query": "label_values(sidecar_server_live{}, source_namespace)"
   },
   {
    "name": "source_service",
    "label": "Source service",
    "query": "label_values(sidecar_server_live{source_namespace=\"$source_namespace\"}, source_service)"
   },
   {
    "name": "destination_service",
    "label": "Destination Service",
    "query": "label_values(sidecar_cluster_upstream_cx_active{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|.*-local|envoy-tracing-cluster|passthrough-outbound\"}, sidecar_cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "Request Count - HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class=\"2\",source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m])",
     "legendFormat": "Time (per minute)"
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class!=\"2\",source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m])",
     "legendFormat": "Time (per minute)"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Connections between services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidecar_cluster_upstream_cx_active{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Traffic from source service perspective",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sidecar_cluster_upstream_cx_tx_bytes_total{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Bytes sent"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_cx_rx_bytes_total{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Bytes received"
    }
   ]
  },
  {
   "title": "Connection/Requests errors from source service perspective",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sidecar_cluster_upstream_cx_destroy_remote_with_active_rq{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Connection destroyed by the client"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_cx_connect_timeout{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Connection timeout"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_cx_destroy_local_with_active_rq{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Connection destroyed by local Sidecar"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_rq_pending_failure_eject{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_rq_pending_overflow{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Pending overflow"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_rq_timeout{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Request timeout"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_rq_rx_reset{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Response reset"
    },
    {
     "expr": "sum(irate(sidecar_cluster_upstream_rq_tx_reset{source_service=\"$source_service\",source_namespace=\"$source_namespace\",sidecar_cluster_name=\"$destination_service\"}[1m]))",
     "legendFormat": "Request reset"
    }
   ]
  }
 ]
}