{
 "title": "OSM Pod to Service Metrics",
 "description": "Compatible with OSM v1.0.0. This dashboard lets you investigate the traffic metrics from a pod to all the services it connects/talks to.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_namespace",
    "label": "Source Namespace",
    "query": "label_values(sidecar_server_live{}, source_namespace)"
   },
   {
    "name": "source_pod",
    "label": "Source Pod",
    "query": "label_values(sidecar_server_live{source_namespace=\"$source_namespace\"}, source_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Request Count - HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Count to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class=\"2\",source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Failure Count to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_xx{sidecar_response_code_class!=\"2\",source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "All types of requests count to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_rq_total{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active Connections to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sidecar_cluster_upstream_cx_active{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection/Requests errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_destroy_remote_with_active_rq{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection destroyed by the client - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_cx_connect_timeout{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection timeout - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_cx_destroy_local_with_active_rq{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Connection destroyed by local Sidecar - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_pending_failure_eject{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Pending failure ejection - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_pending_overflow{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Pending overflow - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_timeout{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Request timeout - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_rx_reset{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Response reset - {{sidecar_cluster_name}}"
    },
    {
     "expr": "irate(sidecar_cluster_upstream_rq_tx_reset{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "Request reset - {{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_rx_bytes_total{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received to other services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(sidecar_cluster_upstream_cx_tx_bytes_total{source_pod_name=\"$source_pod\",source_namespace=\"$source_namespace\",sidecar_cluster_name!~\"osm-controller|envoy-metrics-cluster|envoy-tracing-cluster|passthrough-outbound\"}[1m])",
     "legendFormat": "{{sidecar_cluster_name}}"
    }
   ]
  }
 ]
}