module.exports = {
  lang: process.env.VUE_APP_LANG,
  theme: {
    color: "#00adef",
    mode: "light",
    success: "#52c41a",
    warning: "#faad14",
    error: "#f5222f",
  },
  layout: "side",
  fixedHeader: false,
  fixedSideBar: true,
  fixedTabs: false,
  pageWidth: "fixed",
  weekMode: false,
  multiPage: false,
  cachePage: true,
  hideSetting: false,
  systemName: "Flomesh",
  copyright: "2021 Flomesh",
  asyncRoutes: false,
  showPageTitle: true,
  filterMenu: true,
  animate: {
    disabled: true,
    name: "bounce",
    direction: "left",
  },
  footerLinks: [
    { link: "https://flomesh.io/traffic-guru", name: "Home" },
    { link: "https://github.com/flomesh-io/traffic-guru", icon: "GithubOutlined" },
    { link: "https://flomesh.io", name: "Flomesh.io" },
  ],
};
